export type {
  AssistantTextMessage,
  AssistantToolCallMessage,
  BuildOpenAIRowOptions,
  BusinessContext,
  CliCommandDefinition,
  ConversationMessage,
  ConversationTrajectory,
  DatasetSummary,
  DatasetValidationIssue,
  DatasetValidationResult,
  DeferredLogConversionBoundary,
  ExportMode,
  FineTuningToolkitConfig,
  JsonObject,
  JsonPrimitive,
  JsonSchemaObject,
  JsonSchemaValue,
  JsonValue,
  OpenAIChatFineTuningMessage,
  OpenAIChatFineTuningRow,
  OpenAIToolCall,
  OpenAIToolDefinition,
  PersonaDefinition,
  PublicWorkflow,
  ScenarioDefinition,
  ScenarioPersonaSource,
  ScenarioStoppingRules,
  ScenarioToolInventory,
  SimulatedAssistantTurn,
  SupportedProvider,
  SystemMessage,
  ToolCall,
  ToolResult,
  ToolResultMessage,
  ToolSchema,
  UserMessage,
  ValidationIssue,
  ValidationResult,
  ValidationSummary,
  WorkflowStatus,
} from "./core/index.js";
export type {
  TranslateOpenAIJsonlOptions,
  TranslateOpenAIRowOptions,
  ProviderTranslationAdapterOptions,
  TranslationProviderKind,
  TranslationRequestPath,
  TranslationResult,
  TranslationRules,
  TranslationTextAdapter,
  TranslationTextRequest,
  TranslationWorkflowStatus,
} from "./translation/index.js";
export {
  assertValidOpenAIFineTuningRow,
  bookAppointmentTool,
  bookAppointmentToolTrajectoryFixture,
  buildOpenAIFineTuningRow,
  buildOpenAIFineTuningRows,
  bundledScenarioProfiles,
  checkAvailabilityTool,
  checkAvailabilityToolTrajectoryFixture,
  createDeferredLogConversionError,
  deferredLogConversionBoundary,
  findBundledScenarioProfile,
  fullToolTrajectoryConversationFixture,
  noToolConversationFixture,
  parseScenarioDefinition,
  parseScenarioDefinitionJson,
  receptionistScenarioProfile,
  representativeTrajectories,
  retailSupportScenarioProfile,
  searchTool,
  searchToolTrajectoryFixture,
  serializeOpenAIJsonlRows,
  summarizeOpenAIJsonlRows,
  toolDecisionConversationFixture,
  toolTrajectoryFixtures,
  validateOpenAIJsonl,
  validateOpenAIFineTuningRow,
} from "./core/index.js";
export {
  assertValidLocaleCode,
  createAnthropicTranslationAdapter,
  createOpenAITranslationAdapter,
  createPseudoTranslationAdapter,
  createProviderTranslationAdapter,
  experimentalTranslationRules,
  translateOpenAIFineTuningRow,
  translateDatasetExample,
  translateOpenAIJsonl,
} from "./translation/index.js";
export type {
  AnthropicProviderAdapter,
  CustomProviderAdapter,
  ModelClient,
  ModelInvocationRequest,
  ModelInvocationResponse,
  ModelMessage,
  ModelProviderKind,
  OpenAIProviderAdapter,
  OpenAIResponseRequest,
  ProviderAdapter,
  ProviderClientOptions,
  ProviderEnvironment,
  ProviderErrorOptions,
  ProviderRuntimeConfig,
  AnthropicMessageRequest,
} from "./providers/index.js";
export {
  anthropicProviderAdapter,
  assertSupportedModelProviderKind,
  createModelClientFromConfig,
  createProviderAdapter,
  createUnconfiguredProviderAdapter,
  defaultApiKeyEnvForProvider,
  mapAnthropicMessagesResponse,
  mapModelRequestToAnthropicMessagesRequest,
  mapModelRequestToOpenAIResponsesRequest,
  mapOpenAIResponsesResponse,
  openAIProviderAdapter,
  ProviderAuthenticationError,
  ProviderConfigurationError,
  ProviderError,
  ProviderRateLimitError,
  ProviderResponseError,
  ProviderToolCallError,
  ProviderUnsupportedFeatureError,
  resolveProviderClientOptions,
} from "./providers/index.js";
export type {
  DatasetWriter,
  FileSystemAdapter,
  ModelBackedPersonaGeneratorOptions,
  ModelBackedSimulationRunnerOptions,
  PersonaGenerationRequest,
  PersonaGenerator,
  PersistenceAdapter,
  ScenarioSource,
  ScenarioSourceInput,
  SimulationRequest,
  SimulationRunner,
  SimulationRuntimeAdapters,
  ToolResultProvider,
  ToolResultRequest,
} from "./simulation/index.js";
export {
  buildDeterministicTrajectories,
  buildDeterministicPersonas,
  buildToolArguments,
  createDeferredSimulationRunner,
  createDeterministicPersonaGenerator,
  createDeterministicSimulationRunner,
  createDeterministicToolResultProvider,
  createModelBackedPersonaGenerator,
  createModelBackedSimulationRunner,
  loadScenarioSource,
} from "./simulation/index.js";
import { deferredLogConversionBoundary } from "./core/index.js";
import type { CliCommandDefinition, PublicWorkflow } from "./core/index.js";

export const supportedWorkflows: PublicWorkflow[] = [
  {
    id: "synthetic-dataset-generation",
    status: "v1",
    description: "Generate synthetic chat and tool-calling examples from scenario configs.",
  },
  {
    id: "openai-jsonl-validation",
    status: "v1",
    description: "Validate OpenAI chat fine-tuning JSONL before publishing or training.",
  },
  {
    id: "dataset-translation",
    status: "experimental",
    description: "Localize datasets while preserving tool-call and tool-result structure.",
  },
  {
    id: "log-to-dataset-import",
    status: deferredLogConversionBoundary.status,
    description:
      "Deferred: no v1 real-log converter is shipped until a public source contract, redaction hooks, and privacy-safe fixture coverage exist.",
  },
];

export const cliCommands: CliCommandDefinition[] = [
  {
    name: "simulate-dataset",
    status: "v1",
    description: "Generate a synthetic OpenAI-format JSONL dataset from a scenario config.",
  },
  {
    name: "validate-dataset",
    status: "v1",
    description: "Validate JSONL rows and print a dataset summary.",
  },
  {
    name: "generate-personas",
    status: "v1",
    description: "Generate reusable synthetic personas for a scenario.",
  },
  {
    name: "translate-dataset",
    status: "experimental",
    description: "Translate dataset content while preserving schema-bearing fields.",
  },
  {
    name: deferredLogConversionBoundary.cliCommand,
    status: deferredLogConversionBoundary.status,
    description: "Deferred: no log-derived dataset converter is implemented in v1.",
  },
];
