export type {
  AssistantTextMessage,
  AssistantToolCallMessage,
  BuildOpenAIRowOptions,
  BusinessContext,
  CliCommandDefinition,
  ConversationMessage,
  ConversationTrajectory,
  ExportMode,
  FineTuningToolkitConfig,
  JsonObject,
  JsonPrimitive,
  JsonSchemaObject,
  JsonSchemaValue,
  JsonValue,
  OpenAIChatFineTuningMessage,
  OpenAIChatFineTuningRow,
  OpenAIToolCall,
  OpenAIToolDefinition,
  PersonaDefinition,
  PublicWorkflow,
  ScenarioDefinition,
  ScenarioPersonaSource,
  ScenarioStoppingRules,
  ScenarioToolInventory,
  SimulatedAssistantTurn,
  SupportedProvider,
  SystemMessage,
  ToolCall,
  ToolResult,
  ToolResultMessage,
  ToolSchema,
  UserMessage,
  ValidationIssue,
  ValidationResult,
  ValidationSummary,
  WorkflowStatus,
} from "./core/index.js";
export {
  assertValidOpenAIFineTuningRow,
  bookAppointmentTool,
  bookAppointmentToolTrajectoryFixture,
  buildOpenAIFineTuningRow,
  buildOpenAIFineTuningRows,
  bundledScenarioProfiles,
  checkAvailabilityTool,
  checkAvailabilityToolTrajectoryFixture,
  findBundledScenarioProfile,
  fullToolTrajectoryConversationFixture,
  noToolConversationFixture,
  parseScenarioDefinition,
  parseScenarioDefinitionJson,
  receptionistScenarioProfile,
  representativeTrajectories,
  retailSupportScenarioProfile,
  searchTool,
  searchToolTrajectoryFixture,
  toolDecisionConversationFixture,
  toolTrajectoryFixtures,
  validateOpenAIFineTuningRow,
} from "./core/index.js";
export type {
  AnthropicProviderAdapter,
  CustomProviderAdapter,
  ModelClient,
  ModelInvocationRequest,
  ModelInvocationResponse,
  ModelMessage,
  ModelProviderKind,
  OpenAIProviderAdapter,
  ProviderAdapter,
  ProviderClientOptions,
} from "./providers/index.js";
export {
  anthropicProviderAdapter,
  createUnconfiguredProviderAdapter,
  openAIProviderAdapter,
} from "./providers/index.js";
export type {
  DatasetWriter,
  FileSystemAdapter,
  PersistenceAdapter,
  ScenarioSource,
  ScenarioSourceInput,
  SimulationRequest,
  SimulationRunner,
  SimulationRuntimeAdapters,
} from "./simulation/index.js";
export { createDeferredSimulationRunner, loadScenarioSource } from "./simulation/index.js";
import type { CliCommandDefinition, PublicWorkflow } from "./core/index.js";

export const supportedWorkflows: PublicWorkflow[] = [
  {
    id: "synthetic-dataset-generation",
    status: "v1",
    description: "Generate synthetic chat and tool-calling examples from scenario configs.",
  },
  {
    id: "openai-jsonl-validation",
    status: "v1",
    description: "Validate OpenAI chat fine-tuning JSONL before publishing or training.",
  },
  {
    id: "dataset-translation",
    status: "experimental",
    description: "Localize datasets while preserving tool-call and tool-result structure.",
  },
  {
    id: "log-to-dataset-import",
    status: "deferred",
    description: "Convert redacted production logs into training rows.",
  },
];

export const cliCommands: CliCommandDefinition[] = [
  {
    name: "simulate-dataset",
    status: "v1",
    description: "Generate a synthetic OpenAI-format JSONL dataset from a scenario config.",
  },
  {
    name: "validate-dataset",
    status: "v1",
    description: "Validate JSONL rows and print a dataset summary.",
  },
  {
    name: "generate-personas",
    status: "v1",
    description: "Generate reusable synthetic personas for a scenario.",
  },
  {
    name: "translate-dataset",
    status: "experimental",
    description: "Translate dataset content while preserving schema-bearing fields.",
  },
  {
    name: "convert-logs",
    status: "deferred",
    description: "Convert redacted logs into OpenAI-format rows.",
  },
];
